try {
    throw 42;
} catch (a__4) {
    function a__4() {}
    console.log(a__4);
}
