var a = "FAIL";
try {
    throw 1;
} catch (args__2) {
    var a = "PASS";
}
console.log(a);
