var e = 1;
try {
    throw 2;
} catch (e__2) {
    console.log(e__2);
}
